from fastapi import FastAPI, Depends
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy.orm import Session
from src.database.core import engine, get_db
from src.entities import models
from src import schemas
from typing import List
from sqlalchemy import func

app = FastAPI(title="ContractIQ API")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"], # Your React app URL
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Ensure tables are created
models.Base.metadata.create_all(bind=engine)

@app.get("/health")
def health_check():
    return {"status": "ok"}

# --- NEW: POST Endpoint for Obligations ---
@app.post("/api/obligations")
def create_obligation(obligation: schemas.ObligationCreate, db: Session = Depends(get_db)):
    # 1. Convert the Pydantic schema into a SQLAlchemy model
    new_task = models.Obligation(
        title=obligation.title,
        due_date=obligation.due_date,
        risk_level=obligation.risk_level,
        status=obligation.status,
        responsible_person=obligation.responsible_person,
        contract_id=obligation.contract_id
    )
    
    # 2. Add it to the database session
    db.add(new_task)
    
    # 3. Commit (save) the changes to MySQL
    db.commit()
    
    # 4. Refresh to get the new ID generated by MySQL
    db.refresh(new_task)
    
    return {"message": "Obligation created successfully!", "data": new_task}
@app.get("/api/obligations", response_model=List[schemas.ObligationResponse])
def get_obligations(db: Session = Depends(get_db)):
    # Query the database to get all obligations
    tasks = db.query(models.Obligation).all()
    return tasks

@app.get("/api/dashboard/metrics", response_model=schemas.DashboardMetrics)
def get_dashboard_metrics(db: Session = Depends(get_db)):
    # Count how many contracts have an 'Active' status
    active_contracts = db.query(models.Contract).filter(models.Contract.status == "Active").count()
    
    # Sum up the total financial value of all contracts (returns 0 if empty)
    total_value = db.query(func.sum(models.Contract.value)).scalar() or 0.0
    
    # Count tasks based on their status
    pending_tasks = db.query(models.Obligation).filter(models.Obligation.status != "Completed").count()
    completed_tasks = db.query(models.Obligation).filter(models.Obligation.status == "Completed").count()

    return {
        "active_contracts": active_contracts,
        "total_value": total_value,
        "pending_tasks": pending_tasks,
        "completed_tasks": completed_tasks
    }
@app.put("/api/obligations/{task_id}/status")
def update_obligation_status(task_id: int, status_update: schemas.ObligationStatusUpdate, db: Session = Depends(get_db)):
    # Find the specific task in the database
    task = db.query(models.Obligation).filter(models.Obligation.id == task_id).first()
    
    if task:
        task.status = status_update.status
        db.commit()
        return {"message": "Status updated successfully!"}
    return {"error": "Task not found"}